# Generated by Django 5.2.8 on 2025-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_picker', '0002_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='family',
        ),
        migrations.RemoveField(
            model_name='color',
            name='chroma',
        ),
        migrations.RemoveField(
            model_name='color',
            name='hue',
        ),
        migrations.RemoveField(
            model_name='color',
            name='lightness',
        ),
        migrations.RemoveField(
            model_name='color',
            name='value',
        ),
        migrations.AddField(
            model_name='color',
            name='mode',
            field=models.CharField(blank=True, choices=[('rgb', 'RGB'), ('hsl', 'HSL'), ('oklch', 'OKLCH')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='color',
            name='values',
            field=models.JSONField(default='rgb'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ColorFamily',
        ),
    ]
