# Generated by Django 5.2.8 on 2025-12-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_picker', '0003_remove_color_family_remove_color_chroma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
