# Generated by Django 5.2.8 on 2025-12-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_picker', '0004_alter_color_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('colors', models.ManyToManyField(to='color_picker.color')),
            ],
        ),
    ]
