# Generated by Django 5.2.8 on 2025-12-09 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_picker', '0005_colorfamily'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorfamily',
            name='colors',
        ),
        migrations.AddField(
            model_name='color',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='color_picker.colorfamily'),
        ),
    ]
