# Generated by Django 5.2.8 on 2025-12-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_picker', '0006_remove_colorfamily_colors_color_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
